name: "Build & Release"
on:
  pull_request:
    branches:
      - dev
      - stage
  push:
    branches: 
      - master
      - stage
      - dev

jobs:
  deployDev:
    name: "Deploy to Dev Environment"
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEV_DOMAIN: ${{ secrets.DEV_DOMAIN }}
          file_name: .env_dev
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build --target=lib/main_dev.dart
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v1
        with:
          name: apk-dev-debug
          path: build/app/outputs/flutter-apk/app-dev-debug.apk

  deployProd:
    name: 'Deploy to Production environment'
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEV_DOMAIN: ${{ secrets.DEV_DOMAIN }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.5'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk